/*
 * UNLIKE SERVERAL LANGUAGES
 * SPECIFYING A ENTRY(MAIN) IS NOT SO SMOOTHLY
 * SO NEED THIS HEADER AS CONFIGURATION
 */

/*
 * MUST ONLY ONE DEFINED AS 1 EACH BUILD
 */

#define SAMPLES_FTP_DOWNLOAD	0
#define SAMPLES_FTP_UPLOAD		1

/*
 * HEADERS USED IN SAMPLES
 */

#include <stdio.h>
